### ISSUE TITLE
我按照这个问题解释调整成我自己的节点名字还是不行 报错这个字段有问题

### ISSUE THREAD

**Issue by godzoco** [lusyoe/k8s-local-storage#2]
https://stackoverflow.com/questions/53964239/node-didnt-find-available-persistent-volumes-to-bind

The PersistentVolume "pv141" is invalid: nodeAffinity: Invalid value: core.VolumeNodeAffinity{Required:(*core.NodeSelector)(0xc001d96960)}: field is immutable

**Comment by lusyoe** [comment]
首先我的环境使用的是kubernetes v1.14.0版本，确定环境没问题后。先把已部署的都**清理**掉，再重新`apply`一下看看

**Comment by noelmcloughlin** [comment]
Here is example.
```
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
```
